FROM ubuntu

RUN useradd -m ubuntu && \
    mkdir /home/ubuntu/.ssh && \
    chmod 700 /home/ubuntu/.ssh

COPY key.pub /home/ubuntu/.ssh/authorized_keys

RUN chown ubuntu:ubuntu -R /home/ubuntu && \
    chmod 400 /home/ubuntu/.ssh/authorized_keys

# Install OpenSSH server
RUN apt update && apt install -y openssh-server
RUN mkdir /var/run/sshd

# Expose SSH port
EXPOSE 22

# Start SSH server
CMD ["/usr/sbin/sshd", "-D"]

#### Install Docker ####

RUN apt update && \
apt install -y apt-transport-https ca-certificates curl gnupg lsb-release && \
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
  https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
apt update && \
apt install -y docker-ce docker-ce-cli containerd.io

RUN usermod -aG docker ubuntu

#### Compose ####
RUN curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | \
grep -oP '"tag_name": "\K(.*?)(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
chmod +x /usr/local/bin/docker-compose

